### ISSUE TITLE
Images on hackathons.html are too small on desktop

### ISSUE THREAD

**Issue by dthelegend** [Majonez57/portfolio#1]
**Browser**: Firefox Developer Edition 131
Images are much too small on desktop. Please fix so I can gaze at the glory of these projects.

Image attached
![out](https://github.com/user-attachments/assets/5d1fd909-e691-411f-b65f-41a11767de76)

**Comment by Majonez57** [comment]
Solved in 49cb36d7667e73954b46469bc61c94cc569f07ed.
